#pragma once
#include "Input.h"
#include "resource.h"

void startinit();
GLubyte * LoadDIBitmap(const char *filename, BITMAPINFO **info);
void Fog();
void draw_hp();
int Loadfile();
void renderBitmapString(float x, float y, float z, void *font, char *string);
void letter_Play();
void letter_Menu();
void letter_item();
void letter_time();
void computeDir(float deltaAngle);
void computePos(float deltaMove);
void collision(point a, int i, int j);
void collision_sideline(point a, int i, int j);
void collision_item(point a);
void collision_line(point a);
void collision_endline(point a);
void collision_ghost(point a);
bool warning(point a);
void effectonoff();
void init_board();
void LargeView();
void TopView();
void CameraView();
void Light_1();
void Lantern();
void item();
void remain();
void Person();
void ghost();
void ghost_1();
void drawGreed(void);
void color_change();
void draw_block();
void Line_block();
void board_maker();
void Plane();
void setProjection(int w, int h);
void Reshape(int w1, int h1);
void restorePerspectiveProjection();
void setOrthographicProjection();
void renderScene();
void renderScene2();
void renderScenesw1();
void renderScenesw2();
void renderScenesw3();
void DrawScene();
void Keyboard(unsigned char key, int xx, int yy);
void SpecialKeyboard(int key, int xx, int yy);
void releaseKey(int key, int x, int y);
void MouseMove(int x, int y);
void Mouse(int button, int state, int x, int y);
void TimerFunction(int value);
void init();
void initTextures();
void Replay();
void UI();